version: '3.4'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: gunicorn --bind 0.0.0.0:8000 app:app
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - ${db_host}
    environment:
      - db_user=${db_user}
      - db_pass=${db_pass}
      - db_host=${db_host}
      - db_port=${db_port}
      - db_name=${db_name}
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80  # Change this to whatever host port you want
    networks:
      - app_network
    restart: unless-stopped
   

  db:
    image: postgres:16.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network
    restart: unless-stopped

  startup:
    build:
      context: .
      dockerfile: Dockerfile.startup
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
